swagger: '2.0'
info:
  title: failSchema
  version: '1'
basePath: /api
consumes:
  - application/json
produces:
  - application/json

definitions:
  infoo:
    properties:
      version:
        type: string
    required:
      - version
    type: object

paths:
  /info:
    get:
      description: Get service info
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/infoo'