swagger: '2.0'
info:
  title: sanity
  version: '1'
basePath: /api
consumes:
  - application/json
produces:
  - application/json

definitions:
  infoo:
    properties:
      version:
        type: string
    required:
      - version
    type: object

paths:
  /status:
    get:
      description: Get service status
      produces:
        - text/html
      responses:
        '200':
          description: OK
  /info:
    get:
      description: Get service info
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/infoo'
          x-amples:
            - description: should return info object
              auth: true
              response:
                obj:
                  version: '1.1'