swagger: '2.0'
info:
  title: parameters
  version: '1'
basePath: /api
consumes:
  - application/json
produces:
  - application/json

parameters:
  username:
    description: Username
    in: path
    name: username
    required: true
    type: string

paths:
  /user:
    get:
      description: Get current user
      responses:
        '200':
          description: OK
          x-amples:
            - description: should return a user
              paramProviderFor:
                username: '${obj.username}'
              response:
                obj:
                  username: 'usernameFromGet'
  '/user/{username}':
    parameters:
      - '$ref': '#/parameters/username'
    get:
      description: Get user
      responses:
        '200':
          description: OK
          x-amples:
            - description: should return user
    delete:
      description: Delete user
      parameters:
        - '$ref': '#/parameters/username'
          x-ample: usernameInMethod
      responses:
        '200':
          description: OK
          x-amples:
            - description: should delete user
            - description: should delete another user
              request:
                parameters:
                  username: usernameInExample