swagger: '2.0'
info:
  title: failResponse
  version: '1'
basePath: /api
consumes:
  - application/json
produces:
  - application/json

paths:
  /info:
    get:
      description: Get service info
      responses:
        '200':
          description: OK
          x-amples:
            - description: should return info object
              auth: true
              response:
                obj:
                  version: '1.2'