swagger: '2.0'
info:
  title: swagger-t-str-mock
  version: '1'
  description: This is the mock API specs
basePath: /api
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json

definitions:
  infoo:
    properties:
      version:
        type: string
    required:
      - version
    type: object
    example:
      application/json:
        version: 1.1

paths:
  /status:
    get:
      description: Get service status
      produces:
        - text/html
      responses:
        '200':
          description: OK
  /info:
    get:
      description: Get service info
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/infoo'
          x-amples:
            - description: Test info body
              response:
                body:
                  version: '1.1'
  /auth_token:
    post:
      description: Get auth token for username+password pair
      responses:
        '200':
          description: OK
          x-amples:
            - description: Test auth token ok
              request:
                headers:
                  Authorization: qwe
              response:
                body:
                  auth_token: 'abc'
        '401':
          description: Unauthorized