swagger: '2.0'
info:
  title: swagger-t-str-mock
  version: '1'
  description: This is the mock API specs
basePath: /api
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json

securityDefinitions:
  Basic:
    type: basic
    description: Password auth
    x-ample:
      username: qwe
      password: qwe
  BasicHeader:
    type: basic
    description: Password auth setting header directly
    x-ample: Basic qwe
  Bearer:
    type: apiKey
    description: Token auth
    in: header
    name: Authorization

definitions:
  infoo:
    properties:
      version:
        type: string
    required:
      - version
    type: object
  authToken:
    properties:
      auth_token:
        type: string
    required:
      - auth_token
    type: object

paths:
  /status:
    get:
      description: Get service status
      produces:
        - text/html
      responses:
        '200':
          description: OK
  /info:
    get:
      description: Get service info
      security:
        - Basic: []
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/infoo'
          x-amples:
            - description: should return info object
              auth: true
              response:
                obj:
                  version: '1.1'
  /auth_token:
    post:
      description: Get auth token for username+password pair
      security:
        - BasicHeader: []
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/authToken'
          x-amples:
            - description: should return auth token
              auth: true
              authProviderFor:
                Bearer:
                  x-ample: 'Bearer ${obj.auth_token}'
              response:
                obj:
                  auth_token: 'abc'
        '401':
          description: Unauthorized
  '/auth_token/{token}':
    parameters:
      - description: Token
        in: path
        name: token
        required: true
        type: string
        x-ample: qwe
    put:
      description: Update token
      security:
        - Bearer: []
      responses:
        '200':
          description: OK
          x-amples:
            - description: should update token
              auth: true
              authProviderFor:
                Bearer:
                  x-ample: 'Bearer ${obj.auth_token}'
              request:
                parameters:
                  token: abc
                obj:
                  auth_token: xyz
        '401':
          description: Unauthorized
    delete:
      description: Delete token
      security:
        - Bearer: []
      responses:
        '200':
          description: OK
          x-amples:
            - description: should delete token
              auth: true
              request:
                parameters:
                  token: xyz
        '401':
          description: Unauthorized