swagger: '2.0'
info:
  title: swagger-t-str-mock
  version: '1'
  description: This is the mock API specs
basePath: /api
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json

securityDefinitions:
  Basic:
    type: basic
    description: Password auth
    x-ample: Basic qwe
  Bearer:
    type: apiKey
    description: Token auth
    in: header
    name: Authorization

definitions:
  infoo:
    properties:
      version:
        type: string
    required:
      - version
    type: object
  authToken:
    properties:
      auth_token:
        type: string
    required:
      - auth_token
    type: object

paths:
  /status:
    get:
      description: Get service status
      produces:
        - text/html
      responses:
        '200':
          description: OK
  /info:
    get:
      description: Get service info
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/infoo'
          x-amples:
            - description: should return info object
              response:
                body:
                  version: '1.1'
  /auth_token:
    post:
      description: Get auth token for username+password pair
      security:
        - Basic: []
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/authToken'
          x-amples:
            - description: should return auth token
              auth: true
              authProviderFor:
                Bearer:
                  x-ample: 'Bearer ${body.auth_token}'
              response:
                body:
                  auth_token: 'abc'
        '401':
          description: Unauthorized
  '/auth_token/{token}':
    delete:
      description: Delete token
      security:
        - Bearer: []
      parameters:
        - description: Token
          in: path
          name: token
          required: true
          type: string
      responses:
        '200':
          description: OK
          x-amples:
            - description: should delete token
              auth: true
              request:
                parameters:
                  token: xyz
        '401':
          description: Unauthorized